### ISSUE TITLE
Bug with wechat fingerprint

### ISSUE THREAD

**Issue by EvatsugDnalloR** [eritpchy/FingerprintPay#101]
I've tried the fingerprint modules for Alipay and Wechat, and for Alipay it works perfectly, but for Wechat there's some problem. After i flashed the modules and rebooted, the Wechat crashed and stop functioning, it just can't be opened, stuck when you tap on it. And Once i removed the module for wechat and it starts to work normally. My wechat version is 8.0.9 from google play.

**Comment by eritpchy** [comment]
Cab you upload adb logcat&nbsp; when crash&nbsp; happen?

**Comment by EvatsugDnalloR** [comment]
> Cab you upload adb logcat&nbsp; when crash&nbsp; happen?

yes i will. But maybe this weekend or next weekend if i got time...

**Comment by eritpchy** [comment]
ok

**Comment by EvatsugDnalloR** [comment]
> ok

well i think i maynot go get the logcat anymore cuz i made it works just now... Before i reflash the module i downgraded wechat to 8.0.2 released version instead of the beta one, then i reflash it and the module works properly... maybe it's less helpful for u but at least i got the info that it works on released version of wechat but not beta version...
