### ISSUE TITLE
我成功使用了该模块 但是我是屏下指纹 出现支付的时候 我按哪里都没反应

### ISSUE THREAD

**Issue by SlientTime** [eritpchy/FingerprintPay#105]
我的手机是lg v50s 是屏下指纹 当我选择支付的时候
确实出现了指纹支付的界面 但是屏下指纹支付那个部分不能识别我的指纹 没有显示那个识别区域 我按那个位置也无法识别

**Comment by eritpchy** [comment]
录像看看

**Comment by SlientTime** [comment]
qq给你？怎么给你呀？---- 回复的原邮件 ***@***.***>发送日期2021年09月27日 23:06 ***@***.***> ***@***.******@***.***>主题Re: [eritpchy/FingerprintPay] 我成功使用了该模块 但是我是屏下指纹 出现支付的时候 我按哪里都没反应 (#105)

录像看看



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.



[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/eritpchy/FingerprintPay/issues/105#issuecomment-927964229",

"url": "https://github.com/eritpchy/FingerprintPay/issues/105#issuecomment-927964229",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by eritpchy** [comment]
传到网页上

**Comment by SlientTime** [comment]
Uploading IMG_4772 (2).mp4…

**Comment by SlientTime** [comment]
上传了

**Comment by eritpchy** [comment]
...

**Comment by SlientTime** [comment]
我好像没上传完

**Comment by SlientTime** [comment]
Uploading IMG_4772(1).mp4…

**Comment by SlientTime** [comment]
https://user-images.githubusercontent.com/77520256/134940926-889f065a-8945-4997-8fec-f0fce51e63b0.mp4

**Comment by SlientTime** [comment]
这次应该上传成功了

**Comment by eritpchy** [comment]
再进这里同时抓adb logcat日志发上来

**Comment by SlientTime** [comment]
这个不太会耶

**Comment by eritpchy** [comment]
https://www.pianshen.com/article/66721096210/


自己百度研究下

**Comment by eritpchy** [comment]
no feedback
