### ISSUE TITLE
冷启动支付宝时支付宝会5s后打开但卡死黑屏，要返回桌面后才有可能打开。

### ISSUE THREAD

**Issue by hrqhhrz** [eritpchy/FingerprintPay#107]
冷启动支付宝时支付宝会5s后打开但卡死黑屏，要返回桌面后才有可能打开。
打开支付宝后指纹支付功能正常，关闭模块后支付宝冷启动正常，不知道是怎么回事。
目前机型为红米K40，刷了flyme 9，面具版本23.0，Riru版本26.1.2，模块版本4.0.1
尝试了支付宝的近三个版本和10.2.13.7000版本，都有这个问题
尝试用flyme的LogReport app抓取了从点击支付宝冷启动到返回桌面后支付宝打开过程的log，不知道有没有用

[https://wwe.lanzoui.com/iiBF6uyhorc](url)

**Comment by eritpchy** [comment]
这日志可真详细

**Comment by eritpchy** [comment]
[magisk-riru-module-xfingerprint-pay-alipay-v4.0.2-release.zip](https://github.com/eritpchy/FingerprintPay/files/7291672/magisk-riru-module-xfingerprint-pay-alipay-v4.0.2-release.zip)

感觉是系统的问题
测试这个版本, 先安装好后进入支付宝->设置->指纹设置界面, 确认指纹插件版本是否为4.0.2
记录日志
反馈卡死时间, 尽量精确到秒
上传日志

**Comment by hrqhhrz** [comment]
操作情况：
22:40:52  点击支付宝APP图标
22:40:57  进入支付宝黑屏
22:41:02-03  手动返回桌面，一闪而过的支付宝界面 应该已经成功进入了
22:41:05  再次点击支付宝APP，已经是正常进入了

录了个屏，看起来应该能更直观点吧。。。

https://user-images.githubusercontent.com/58965222/136228094-d6252e1b-cde4-44c4-b2d8-90b323e90e69.mp4

[21-10-6--22-40-50.zip](https://github.com/eritpchy/FingerprintPay/files/7295008/21-10-6--22-40-50.zip)

**Comment by eritpchy** [comment]
复制 /system/framework/libriru-module-xfingerprint-pay-alipay.dex  到 /data/local/tmp/libriru-module-xfingerprint-pay-alipay.dex  试试, 并给权限777

**Comment by eritpchy** [comment]
magisk坏了？ 重装magisk看看？

**Comment by eritpchy** [comment]
[magisk-riru-module-xfingerprint-pay-alipay-v4.0.3-release.zip](https://github.com/eritpchy/FingerprintPay/files/7309977/magisk-riru-module-xfingerprint-pay-alipay-v4.0.3-release.zip)
测试这个版本, 确认版本号为4.0.3, 无论成功与否再抓一次日志, 不用反馈卡死时间
安装模块前先手动删除一次/data/local/tmp/libriru-module-xfingerprint-pay-alipay.dex文件

**Comment by hrqhhrz** [comment]
这个版本可以正常启动支付宝，模块刷入后发现在/data/local/tmp下出现了一个libriru-module-xfingerprint-pay-alipay.dex文件，权限为644，日志见附件，不知道为啥这次录制log时间比之前都短但大了很多。。。看了下里面多了个modemcrash的文件夹
附件好像太大传不上来，我传在网盘了
https://wwe.lanzoui.com/iBNw1v3zu6f

**Comment by eritpchy** [comment]
[magisk-riru-module-xfingerprint-pay-alipay-v4.0.1-release.zip](https://github.com/eritpchy/FingerprintPay/files/7315139/magisk-riru-module-xfingerprint-pay-alipay-v4.0.1-release.zip)
改低了版本号, 没问题就先用着这个版本,
