### ISSUE TITLE
能否适配下Zygisk？

### ISSUE THREAD

**Issue by fantasy467** [eritpchy/FingerprintPay#111]
正在使用的模块就差个别还没适配Zygisk了，所以还是没法启用

**Comment by eritpchy** [comment]
maybe

**Comment by edwin-wang** [comment]
非常需要这个～～～

**Comment by fang5566** [comment]
> 非常需要这个～～～
我现在用lsp的zygisk版本，然后安装xp版的指纹支付。

**Comment by ec-to** [comment]
+1

**Comment by Youmdzz2333** [comment]
确实很需要

**Comment by eritpchy** [comment]
fixed [v4.2.1](https://github.com/eritpchy/FingerprintPay/releases/tag/4.2.1-ci)
