### ISSUE TITLE
Use BiometricPrompt on API 28+

### ISSUE THREAD

**Issue by mochaaP** [eritpchy/FingerprintPay#112]
xref: #86 #17 

Source: <https://developer.android.com/reference/androidx/biometric/BiometricPrompt>

BiometricPrompt 由系统提供多种生物验证支持。在有不同生物验证方式的设备上，（即使是在 Work Profile 或多用户中）都可以工作。

目前使用的 FingerprintManager 在 API 28+ 被标记为废弃，且不可用。

> This class was deprecated in API level 28.
See BiometricPrompt which shows a system-provided dialog upon starting authentication. In a world where devices may have different types of biometric authentication, it's much more realistic to have a system-provided authentication dialog since the method may vary by vendor/device.
> <https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager>

外部依赖 [FingerprintIdentify](https://github.com/uccmawei/FingerprintIdentify) 没有对 BiometricPrompt 进行适配，并且在 2022 年的今天，我们没有必要使用它来兼容这些十分老旧，不支持常规 API 的设备了。

**Comment by eritpchy** [comment]
别提了，早期就调研过， 这个软件的实现方式和普通的安卓app有很大区别，实际上不一定很容易能用上，你有兴趣可以自己试试，这货还支持人脸识别，加密储存呢， api过时不代表不能用， 直到谷歌删除api那一天再说， 我开发设备api 30 31不一样跑着很顺？
