### ISSUE TITLE
支付密码错误

### ISSUE THREAD

**Issue by starslightbright** [eritpchy/FingerprintPay#113]
magisk版本23.0，riru版本26.1.4.r522，模块版本4.0.1，微信版本8.0.18，在模块设置好正确密码，支付时提示密码错误

**Comment by eritpchy** [comment]
1. 支付密码是否输错
2. 回退上一个版本微信是否有问题
3. 重启手机后是否表现一样

**Comment by w2015long** [comment]
同样的 微信版本8.0.18，在模块设置好正确密码，支付时提示密码错误

**Comment by starslightbright** [comment]
> 

密码正确无误，已经尝试五遍以上，重启无效。目前商店最新版本8.0.16正常，8.0.17非商店版本没有包不能确定。

**Comment by fang5566** [comment]
酷安也有好几个反馈，应该是适配问题，请大佬测试一下

**Comment by eritpchy** [comment]
fixed [v4.2.1](https://github.com/eritpchy/FingerprintPay/releases/tag/4.2.1-ci)
