### ISSUE TITLE
riru-core不识别该模块，支付宝里无相关入口

### ISSUE THREAD

**Issue by Aric-Sun** [eritpchy/FingerprintPay#116]
Android 11，类原生DotOS 5.2.1
Magisk 558710bb-alpha-2 (23016) ，Magisk模块页里两个指纹支付模块都是启用状态
Riru v26.1.4.r522.8b379cedb5，不是在模块页显示载入了几个模块嘛，就没有支付宝和淘宝的指纹支付。
alipay 10.2.30.6427 （play，API30）
Magisk 启动日志：[magisk_log_2022-01-18T09_41_17.759.log](https://github.com/eritpchy/FingerprintPay/files/7885518/magisk_log_2022-01-18T09_41_17.759.log)

**Comment by Aric-Sun** [comment]
用的是`riru-module-xfingerprint-pay-alipay-v4.2.0-release.zip`和`riru-module-xfingerprint-pay-taobao-v4.2.0-release.zip`

**Comment by heptaspirit** [comment]
出现了同样的问题，
一加7pro，android11，magisk 23016，riru v26.1.4.r522.8b379cedb5
显示没有加载相应的支付模块

**Comment by eritpchy** [comment]
[Magisk_92546e8a](https://raw.githubusercontent.com/topjohnwu/magisk-files/canary/app-debug.apk) 试试

**Comment by eritpchy** [comment]
1. 截图magisk首页, 模块页
2. lsposed以及lsposed的模块是否工作正常
3. riru 微信, qq是否工作正常
4. 抓adb logcat

**Comment by Aric-Sun** [comment]
暂时离不开Magisk-alpha的MagiskHide，所以很抱歉不能尝试原版的[Magisk_92546e8a](https://raw.githubusercontent.com/topjohnwu/magisk-files/canary/app-debug.apk) 
没有用LSPosed模块，也没有用qq/wx的支付模块。
由于暂时要用，我先回退版本了，有时间给你抓log。Logcat Reader这个app也行的吧

**Comment by lukepushsolo** [comment]
Pixel XL，android 10，magisk 23000，riru v26.1.3.r513.8e95115fd4，wechat play版8.0.15
我这bug更离谱，昨晚更新riru-module-xfingerprint-pay-wechat-v4.2.0-release.zip这个包后，riru无法识别该模块，微信启动直接黑屏卡死。
回退刷了magisk-riru-module-xfingerprint-pay-wechat-v4.0.1-release.zip这个包后riru可以识别模块，但是微信仍然无法启动，只有删除这个模块微信才能正常启动。
准备晚上备份微信重新安装再看看。

**Comment by eritpchy** [comment]
只是让你试试magisk canary是不是正常, 没让你一直用

**Comment by Aric-Sun** [comment]
@lukepushsolo 需要把`/data/local/tmp`下的两个dex删了，我一开始也是卡死，清除app数据都没用，还是看的[ussue#107](https://github.com/eritpchy/FingerprintPay/issues/107) 才知道要删点东西

**Comment by Aric-Sun** [comment]
@eritpchy alpha和原版不兼容，需要彻底卸载然后再装jw的版本，成本挺高的，要重配denylist/MagiskHide List，以及重装模块。

**Comment by lukepushsolo** [comment]
> @lukepushsolo 需要把`/data/local/tmp`下的两个dex删了，我一开始也是卡死，清除app数据都没用，还是看的[ussue#107](https://github.com/eritpchy/FingerprintPay/issues/107) 才知道要删点东西

还真是，dex文件删完后微信能正常启动了

**Comment by timberdai** [comment]
> 出现了同样的问题， 一加7pro，android11，magisk 23016，riru v26.1.4.r522.8b379cedb5 显示没有加载相应的支付模块

+1

**Comment by eritpchy** [comment]
fixed [v4.2.1](https://github.com/eritpchy/FingerprintPay/releases/tag/4.2.1-ci)
