### ISSUE TITLE
riru无法识别模块，用不了指纹支付

### ISSUE THREAD

**Issue by A350-900** [eritpchy/FingerprintPay#117]
![Screenshot_20220118-105520_Magisk](https://user-images.githubusercontent.com/75476713/149862971-333f2e7c-7ca0-4ec5-9ca5-ecb0fc62e836.png)
![Screenshot_20220118-105538_微信](https://user-images.githubusercontent.com/75476713/149862977-f8e23027-e23c-49d2-b826-7b7e1ed38227.png)
如题

**Comment by eritpchy** [comment]
重启手机

**Comment by A350-900** [comment]
> 重启手机

试过了，没用，还是识别不出来

**Comment by eritpchy** [comment]
magisk 什么版本

**Comment by A350-900** [comment]
> magisk 什么版本

![Uploading Screenshot_20220118-112842_Magisk.png…]()

**Comment by A350-900** [comment]
> magisk 什么版本

![Screenshot_20220118-112842_Magisk](https://user-images.githubusercontent.com/75476713/149866140-917eeaef-21a7-4360-aec0-ece869f5be16.png)

**Comment by eritpchy** [comment]
fixed [v4.2.1](https://github.com/eritpchy/FingerprintPay/releases/tag/4.2.1-ci)
