### ISSUE TITLE
无法识别到微信支付4.2版本

### ISSUE THREAD

**Issue by MikuMaxZ** [eritpchy/FingerprintPay#118]
Magisk版本是alpha-3，Riru是V26.1.4.r522.8b379cedb5，但是无法识别到riru版本的微信支付。

**Comment by MikuMaxZ** [comment]
用4.01的就可以

**Comment by Marsmawei** [comment]
4.0.2什么时候能用呀

**Comment by eritpchy** [comment]
fixed on https://github.com/eritpchy/FingerprintPay/releases/tag/4.2.1-ci
