### ISSUE TITLE
指纹支付错误问题

### ISSUE THREAD

**Issue by coolkai** [eritpchy/FingerprintPay#120]
play版8.0.15 问题：
转账、红包等支付方式 不会有问题 ；但扫码支付的时候会出现 ”多次尝试错误，请xxxxx“；
然后第二次扫描支付不会有这个报错，过段时间使用又会有

**Comment by coolkai** [comment]
play版微信；目前仅使用微信指纹

**Comment by eritpchy** [comment]
1

**Comment by coolkai** [comment]
转账、红包等支付方式也会有问题了。。多次尝试错误，请使用密码支付

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/FingerprintPay/releases/tag/4.3.1-ci
