### ISSUE TITLE
Play应用商店报毒

### ISSUE THREAD

**Issue by 205687875** [eritpchy/FingerprintPay#121]
前几天更新之后忽然报毒了 更新之前没有出现过大佬有办法让它不报毒吗
![Screenshot_20220121-164431_Google Play 商店](https://user-images.githubusercontent.com/60597156/150495165-2c879e54-ee57-4dde-ab93-58bd4527b5c8.png)

**Comment by eritpchy** [comment]
1

**Comment by Krisolthokaran** [comment]
关了扫描重新开，老毛病了

**Comment by eritpchy** [comment]
![Cache_184943a212c2f41f](https://user-images.githubusercontent.com/8630635/152157418-b975a31b-adb9-4292-a054-dd49ea5a0e62.jpg)
气不

**Comment by Originalimoc** [comment]
问题一：什么叫毒🌚

**Comment by eritpchy** [comment]
old
