### ISSUE TITLE
4.3.0 导致电信断网。。。

### ISSUE THREAD

**Issue by baimablog** [eritpchy/FingerprintPay#123]
我一加七手机，magisk23.0正式版。riru26版本。装的最新的lsposed。刚刚弹出4.3.0更新的，就升级了，重启之后手机连不上网络了。在lsposed禁用模块后重启网络恢复。不知道是不是这个模块导致的。大佬有空看看？

**Comment by eritpchy** [comment]
可能是重启命令的问题, 请重启两次手机

**Comment by eritpchy** [comment]
你是用magisk的重启功能还是手机自带的重启

**Comment by baimablog** [comment]
自带的重启功能。

**Comment by eritpchy** [comment]
这个模块没那么强

**Comment by eritpchy** [comment]
old
