### ISSUE TITLE
能否去除指纹验证成功的提示  指纹设置移至二级菜单

### ISSUE THREAD

**Issue by smyhm** [eritpchy/FingerprintPay#129]
提示验证成功提示感觉很鸡肋，每次使用指纹都会挡在屏幕中间
指纹设置建议移动至原版二级菜单，或者移动至设置页最底部，这样不会对选项位置有影响

**Comment by eritpchy** [comment]
置后，搞不来

**Comment by smyhm** [comment]
> 

验证成功提示，可以在通知里禁用所有通知，就没了。

**Comment by eritpchy** [comment]
https://github.com/eritpchy/FingerprintPay/commit/804be7db07b6ea870e2c2bc1f8d32644bcc49818
