### ISSUE TITLE
云闪付换卡后无法指纹支付

### ISSUE THREAD

**Issue by RichardZhang4** [eritpchy/FingerprintPay#130]
银联云闪付优先选择的卡可以指纹，点叉换卡继续支付就不能用了

**Comment by eritpchy** [comment]
无法重现, 请更新至[4.4.0](https://github.com/eritpchy/FingerprintPay/releases/tag/4.4.0-ci),再次尝试, 并录像

**Comment by EdiTurn** [comment]
在扫微信或支付宝的二维码付款时遇到过，刚才试了一下，对这个问题做一些补充：
未启用指纹模块时的流程：
扫码 - 输入金额 - 点击“付款” - 出现付款详情界面（在此可以选择付款方式） - 点击“确认付款” - 输密码
启用模块后的流程：
扫码 - 输入金额 - 点击“付款” - 出现付款详情界面（此时立刻弹出指纹验证） - 取消指纹验证、点击“确认付款” - 跳到输密码界面

以上测试在 4.4.0 上完成，且过程中发现，在指纹设置中不选择“启用”，仍然弹出指纹验证。

**Comment by RichardZhang4** [comment]
> 在扫微信或支付宝的二维码付款时遇到过，刚才试了一下，对这个问题做一些补充： 未启用指纹模块时的流程： 扫码 - 输入金额 - 点击“付款” - 出现付款详情界面（在此可以选择付款方式） - 点击“确认付款” - 输密码 启用模块后的流程： 扫码 - 输入金额 - 点击“付款” - 出现付款详情界面（此时立刻弹出指纹验证） - 取消指纹验证、点击“确认付款” - 跳到输密码界面
> 
> 主要问题可能在于过早地弹出了指纹验证，以至于如需选择付款方式必须先取消指纹验证。
> 
> 以上测试在 4.4.0 上完成，且过程中发现，在指纹设置中不选择“启用”，仍然弹出指纹验证。

对，我说的是：扫码 - 输入金额 - 点击付款 - 出现付款详情界面（此时立刻弹出指纹验证）- 取消指纹验证、点击继续付款 - 更换银行卡 - 确认支付 - 跳到输密码界面，这个时候就无法指纹支付了

4.4.0 也是有这个问题的，感觉是云闪付的问题，微信是可以的

**Comment by eritpchy** [comment]
已经试图修复, 请测试 [zygisk-module-xfingerprint-pay-unionpay-v4.4.4-release.zip](https://github.com/eritpchy/FingerprintPay/files/8387817/zygisk-module-xfingerprint-pay-unionpay-v4.4.4-release.zip)

**Comment by EdiTurn** [comment]
确认已修复

**Comment by curx95** [comment]
> 已经试图修复, 请测试 [zygisk-module-xfingerprint-pay-unionpay-v4.4.4-release.zip](https://github.com/eritpchy/FingerprintPay/files/8387817/zygisk-module-xfingerprint-pay-unionpay-v4.4.4-release.zip)

magisk版本同样存在问题，请问是否可修复
