### ISSUE TITLE
云闪付在支付成功界面会再次弹出指纹验证

### ISSUE THREAD

**Issue by EdiTurn** [eritpchy/FingerprintPay#133]
系统版本：OxygenOS 12
云闪付版本：9.1.1 play 版
插件版本：4.4.0 Zygisk

日志：
[log.txt](https://github.com/eritpchy/FingerprintPay/files/8378192/log.txt)

**Comment by eritpchy** [comment]
录像看看

**Comment by eritpchy** [comment]
是每次都弹还是偶尔弹

**Comment by EdiTurn** [comment]
每次使用都弹。

**Comment by EdiTurn** [comment]
https://user-images.githubusercontent.com/5492805/160781443-871b79c2-453d-4ead-aa7b-e2cefda2713d.mp4

**Comment by eritpchy** [comment]
这个页面我没有条件测试, 请装这个包并抓日志(并未修复), 当然如果能提供账号测试那更好
[zygisk-module-xfingerprint-pay-unionpay-v4.4.1-release.zip](https://github.com/eritpchy/FingerprintPay/files/8378428/zygisk-module-xfingerprint-pay-unionpay-v4.4.1-release.zip)

**Comment by EdiTurn** [comment]
[log4.4.1.txt](https://github.com/eritpchy/FingerprintPay/files/8378637/log4.4.1.txt)

**Comment by eritpchy** [comment]
已经试图修复, 请测试
[zygisk-module-xfingerprint-pay-unionpay-v4.4.2-release.zip](https://github.com/eritpchy/FingerprintPay/files/8385926/zygisk-module-xfingerprint-pay-unionpay-v4.4.2-release.zip)

**Comment by EdiTurn** [comment]
问题在还款场景及解绑卡片场景都依然存在。
[4.4.2.log](https://github.com/eritpchy/FingerprintPay/files/8385990/4.4.2.log)

**Comment by eritpchy** [comment]
解绑卡片录像看看

**Comment by EdiTurn** [comment]
https://user-images.githubusercontent.com/5492805/160993783-6e175ca3-e607-48d2-8f47-24eb60f0aaff.mp4

[4.4.2-2.log](https://github.com/eritpchy/FingerprintPay/files/8386652/4.4.2-2.log)

**Comment by eritpchy** [comment]
再试试 [zygisk-module-xfingerprint-pay-unionpay-v4.4.3-release.zip](https://github.com/eritpchy/FingerprintPay/files/8386761/zygisk-module-xfingerprint-pay-unionpay-v4.4.3-release.zip)

**Comment by EdiTurn** [comment]
已确认上述两个场景的再弹出问题都已经解决，多谢。

**Comment by naicfeng** [comment]
xp版也有此情况，症状表现和视频相同，请求有空修复一下！😘😘😘 @eritpchy
