### ISSUE TITLE
［功能请求］支持京东的指纹支付

### ISSUE THREAD

**Issue by NextAlone** [eritpchy/FingerprintPay#134]
![Screenshot_2022-03-31-16-01-46-95_4fbb30eb7b7166119bd25e41eddeee2f.jpg](https://user-images.githubusercontent.com/12210746/161007063-61bd1092-041e-466b-9ac6-95ad70cd37c9.jpg)

无法开启

**Comment by eritpchy** [comment]
是的, 没打算支持
