### ISSUE TITLE
Add new Magisk auto-update support

### ISSUE THREAD

**Issue by cc9014** [eritpchy/FingerprintPay#136]
Shamiko, LSPosed, Sui are all support this feature. (add updateJson)

**Comment by eritpchy** [comment]
1

**Comment by eritpchy** [comment]
https://github.com/eritpchy/FingerprintPay/releases/tag/4.5.0-ci

**Comment by cc9014** [comment]
感谢更新，但安装v4.5.0后面具中更新的图标还是亮起蓝色，但实际已经是最新版。通过app内再次更新重启后还是这样。
