### ISSUE TITLE
添加国外信用卡时，指纹模块会自动弹出并打断添加过程

### ISSUE THREAD

**Issue by sakuyamaij** [eritpchy/FingerprintPay#140]
模块版本4.4.0
微信play最新版

流程如下：
1. 添加银行卡
2.输入信用卡卡号，点下一步，进入输入信用卡详细信息界面
3. 在该界面下，选择信用卡所属国家地区时
比如我是选择的，美国-xx州-xx地区
选择后弹出指纹模块，指纹认证成功后界面返回步骤2的填写信用卡卡号
形成了一个循环

关闭指纹模块后，可正常添加国外信用卡

**Comment by eritpchy** [comment]
我国区的账户没办法测试这个流程, 请提供相应日志或者测试账号, 谢谢

**Comment by sakuyamaij** [comment]
我是国区账号，该行为和信用卡是否为国外信用卡有关。
可以测试下添加5178 0595 1111 1111
微信可识别为mastercard

**Comment by eritpchy** [comment]
印象中解决了
