### ISSUE TITLE
在设置内输入密码界面中点击“确定”后，输入法未关闭

### ISSUE THREAD

**Issue by wordlesswind** [eritpchy/FingerprintPay#145]
![Screenshot_2022-08-04-21-47-33-70_e39d2c7de19156b0683cd93e8735f348](https://user-images.githubusercontent.com/9050713/182863245-0629bb52-7953-44e9-bf3f-7071ca0eb009.jpg)
交互上的小问题，如果能优化的话，就更好了。

ColorOS 12.1 (Android 12)
Zygisk (Magisk 25.2)

**Comment by eritpchy** [comment]
1

**Comment by eritpchy** [comment]
https://github.com/eritpchy/FingerprintPay/releases/tag/4.5.0-ci
