### ISSUE TITLE
调用指纹重启

### ISSUE THREAD

**Issue by Amamiya23** [eritpchy/FingerprintPay#146]
在安卓13上，用这个模块，微信支付的时候调用系统指纹会直接卡重启。

**Comment by eritpchy** [comment]
有趣，不过我没有设备，自己抓下adb logcat?

**Comment by Amamiya23** [comment]
[logcat.log](https://github.com/eritpchy/FingerprintPay/files/9797681/logcat.log)
我随便抓的，不知道是不是你这个模块的问题

**Comment by eritpchy** [comment]
用magisk版试试

**Comment by eritpchy** [comment]
old
