### ISSUE TITLE
［非中文环境微信］指纹模块设置不显示

### ISSUE THREAD

**Issue by AzusaHana** [eritpchy/FingerprintPay#150]
Play 版微信 8.8.30（2244）
模块版本 4.5.0
测试环境：日文
切换中文显示模块设置，可以正常设置密码
切换日文则不显示，在中文环境已经设置好的可以继续使用

**Comment by AzusaHana** [comment]
> 这个确实不支持, 因为他要靠设置页的文本来定位, 不过你可以试试支付设置页能不能看到.

支付页现在改版了，以前那个点不出来变成了服务管理，只能在设置页设置，在中文环境设置好在其他语言就能用了，这个影响不是很大

**Comment by eritpchy** [comment]
嗯, 暂时先这样
