### ISSUE TITLE
更新基于安卓13的miui14后开机黑屏进fastboot

### ISSUE THREAD

**Issue by hosea666** [eritpchy/FingerprintPay#152]
使用的zygisk版，更新后开启模块重启后，大概十几秒就会黑屏然后重启进fastboot，重装几次没有解决，本以为是适配问题但是好像没有别人反馈

**Comment by eritpchy** [comment]
miui不是有全功能root吗？装这个干啥。

**Comment by eritpchy** [comment]
同环境没有发现这个现象
