### ISSUE TITLE
Zygisk微信指纹无效（Play版8.0.30）

### ISSUE THREAD

**Issue by GenTort666** [eritpchy/FingerprintPay#154]
使用Zygisk+LSPosed，从Google Play获取的微信，模块设置可正常打开，但是尝试开启指纹支付仍提示“系统错误，可删除系统指纹，重新录入后再试”

**Comment by eritpchy** [comment]
没有这个提示就不需要用模块了

**Comment by Dreamray** [comment]
开启模块后，微信里的设置就不用管了，去付款吧，默认就是指纹支付了。

但还有一个小问题，付完款后微信提示我开启指纹支付
