### ISSUE TITLE
微信支付无法输入密码

### ISSUE THREAD

**Issue by beixinti** [eritpchy/FingerprintPay#155]
指纹支付正常，点击指纹图标手动输入密码键盘无法打出密码。复现概率100%  

机型：motorolaEdgeS Android11
微信：8.0.21 Play版
模块：4.6.0 lsposed加载  

![Screenshot_20230122-093700.png](https://user-images.githubusercontent.com/95170151/213896898-b38b01ff-8b30-4195-92c0-73ee33338b4b.png)

**Comment by eritpchy** [comment]
1

**Comment by beixinti** [comment]
# ¿

**Comment by huxc573** [comment]
moto edge s pro 安卓12，微信版本相同，4.6.0 lsposed指纹支付图标过大，退回4.5.0无此问题。

**Comment by eritpchy** [comment]
截图

**Comment by eritpchy** [comment]
更新4.7.0试试
