### ISSUE TITLE
4.6.0 微信模块 zgisk版本 影响 Xperia 1 II 快充

### ISSUE THREAD

**Issue by utf8-coding** [eritpchy/FingerprintPay#159]
启动模块会导致无法使用快充（PD 15W “快充”），兼容快充协议的设备会直接无法充电。慢充不受影响。

系统不是原生，是官版 LineageOS 20。

**Comment by eritpchy** [comment]
没有该手机，您可以尝试以下步骤确定问题。
1. 从zip包中删除一个文件, 后缀名为so或dex
2. magisk中安装, 并重启手机
3. 确认问题是否出现, 问题不出现则换一个文件删除, 请确保每次只删除了1个文件, 重复步骤123

**Comment by eritpchy** [comment]
有空试试4.7.0

**Comment by xunsum** [comment]
好的，我现在在使用独立的微信版本。没有BUG。

**Comment by eritpchy** [comment]
是内嵌本模块功能的微信版本?
