### ISSUE TITLE
支付宝总设置页面不显示指纹支付设置，无法设置密码

### ISSUE THREAD

**Issue by jcsolely** [eritpchy/FingerprintPay#160]
支付时可以调起指纹控件，但是提示未设置密码

**Comment by jcsolely** [comment]
Magisk Manager与LSPosed版都试了问题一样

**Comment by eritpchy** [comment]
版本

**Comment by jcsolely** [comment]
指纹版本4.6.0

**Comment by jcsolely** [comment]
微信与QQ及云闪付正常使用

**Comment by jcsolely** [comment]
支付宝版本10.3.70

**Comment by eritpchy** [comment]
支付宝版本

**Comment by eritpchy** [comment]
哦

**Comment by N2022062** [comment]
臨時方法 先裝低版設置好再升級

**Comment by eritpchy** [comment]
fixed https://github.com/eritpchy/FingerprintPay/releases/tag/4.7.0-ci

**Comment by eritpchy** [comment]
软件版本

**Comment by 54271** [comment]
支付宝10.3.86.8000
模块zygisk 4.7.1

**Comment by eritpchy** [comment]
进到该有设置入口的地方截图看看

**Comment by 54271** [comment]
![Screenshot_20230615-205356](https://github.com/eritpchy/FingerprintPay/assets/51184950/6577bd19-ee30-4988-be01-7e7eb4e7f697)
![Screenshot_20230615-205347](https://github.com/eritpchy/FingerprintPay/assets/51184950/8fdd8cbc-283a-41d9-93df-83c31d41d3e0)
![Screenshot_20230615-205408](https://github.com/eritpchy/FingerprintPay/assets/51184950/d10be1e7-65f4-408a-908a-6ff2c3850d2d)

**Comment by eritpchy** [comment]
抓 adb logcat发上来

**Comment by eritpchy** [comment]
再看看支付宝的版本号数字

**Comment by 54271** [comment]
![Screenshot_20230615-210814](https://github.com/eritpchy/FingerprintPay/assets/51184950/85d3915d-9420-455b-8a1d-308f9f0574d0)
比更新日志里的适配版本新一点

**Comment by eritpchy** [comment]
发上来

**Comment by 54271** [comment]
发支付宝安装包还是log？

**Comment by eritpchy** [comment]
都要, 你还是先发log, 我试了下最新版还是正常

**Comment by 54271** [comment]
行 晚点回家发你

**Comment by geoleonsh** [comment]
同版本支付宝没设置入口

**Comment by 54271** [comment]
4.7.3模块有设置入口了
