### ISSUE TITLE
4.6.0 安装zygisk模块失败

### ISSUE THREAD

**Issue by xmhwws** [eritpchy/FingerprintPay#161]
安装`zygisk-module-xfingerprint-pay-all-v4.6.0-release.zip`
一直是这个错误，不知道为什么？
安卓11

![image](https://user-images.githubusercontent.com/42903751/235447917-17c17b3d-7634-4318-a6ce-447d0571972a.png)

但是，安装`zygisk-module-xfingerprint-pay-alipay-v4.6.0-release.zip`就没有问题

![image](https://user-images.githubusercontent.com/42903751/235448232-f94491d0-9571-4478-ae76-432a2d7ba9c3.png)

**Comment by eritpchy** [comment]
这个要解压缩
