### ISSUE TITLE
Momo:Found Zygisk

### ISSUE THREAD

**Issue by sunday123** [eritpchy/FingerprintPay#163]
zygisk-module-xfingerprint-pay-alipay-release 
版本:4.6.0

导致的问题，Momo检测到了Zygisk

**Comment by eritpchy** [comment]
?

**Comment by sunday123** [comment]
> ?

![image](https://github.com/eritpchy/FingerprintPay/assets/9637770/83c7433f-501f-4a36-9213-9a5a429f6b02)


安装 zygisk-module-xfingerprint-pay-alipay-release 模块
引起了环境异常。

**Comment by eritpchy** [comment]
实测没装模块也能检测到

**Comment by sunday123** [comment]
> 实测没装模块也能检测到

我测的不是这样。

我把magisk里面zygisk-module-xfingerprint-pay-alipay 的沟关闭重启发现检测不到了
![Screenshot_20230608-164223_Momo](https://github.com/eritpchy/FingerprintPay/assets/9637770/0c8a6692-baf3-486f-a99e-78e9b91910c6)
这图是zygisk-module-xfingerprint-pay-alipay模块启用状态的


![Screenshot_20230608-164346_Momo](https://github.com/eritpchy/FingerprintPay/assets/9637770/3e93c711-0f28-4d6c-8439-b6bae6ab405a)

这图是zygisk-module-xfingerprint-pay-alipay模块关闭重启状态的

**Comment by eritpchy** [comment]
[zygisk-module-xfingerprint-pay-alipay-v4.6.1-release.zip](https://github.com/eritpchy/FingerprintPay/files/11690086/zygisk-module-xfingerprint-pay-alipay-v4.6.1-release.zip)
试试

**Comment by sunday123** [comment]
> [zygisk-module-xfingerprint-pay-alipay-v4.6.1-release.zip](https://github.com/eritpchy/FingerprintPay/files/11690086/zygisk-module-xfingerprint-pay-alipay-v4.6.1-release.zip) 试试

4.6.1 已经解决了Found Zygisk

**Comment by sunday123** [comment]
4.6.1 已经解决了
