### ISSUE TITLE
请验证指纹五个字不居中

### ISSUE THREAD

**Issue by sigako** [eritpchy/FingerprintPay#164]
看着好难受

**Comment by catshitz** [comment]
好家伙 要么半年不更新 要么一更新如串稀 还是等稳定再来吧

**Comment by sigako** [comment]
> 好家伙 要么半年不更新 要么一更新如串稀 还是等稳定再来吧

这个问题一直存在，并不是最近版本更新出现的

**Comment by eritpchy** [comment]
截图

**Comment by sigako** [comment]
> 截图
![Screenshot_20230616-095743](https://github.com/eritpchy/FingerprintPay/assets/136769215/67a5911b-80b4-44f6-b209-748bf13fd306)

**Comment by eritpchy** [comment]
这个实在难调, 他本来就有点歪, 我已经加了几个空格了 他还是有点歪, 再多一个空格, ta更歪

**Comment by eritpchy** [comment]
[zygisk-module-xfingerprint-pay-wechat-v4.7.3-release.zip](https://github.com/eritpchy/FingerprintPay/files/11765486/zygisk-module-xfingerprint-pay-wechat-v4.7.3-release.zip)
试试

**Comment by sigako** [comment]
> [zygisk-module-xfingerprint-pay-wechat-v4.7.3-release.zip](https://github.com/eritpchy/FingerprintPay/files/11765486/zygisk-module-xfingerprint-pay-wechat-v4.7.3-release.zip) 试试

舒服了

**Comment by eritpchy** [comment]
行

**Comment by eritpchy** [comment]
fixed
