### ISSUE TITLE
play淘宝失效

### ISSUE THREAD

**Issue by FFeei** [eritpchy/FingerprintPay#168]
设置里有入口，但是支付还是密码~

感谢作者付出

**Comment by FFeei** [comment]
10.22.10.23版本号 安卓12 索尼xperia 1 II

**Comment by eritpchy** [comment]
[zygisk-module-xfingerprint-pay-taobao-v4.7.5-release.zip](https://github.com/eritpchy/FingerprintPay/files/11779025/zygisk-module-xfingerprint-pay-taobao-v4.7.5-release.zip)
请测试

**Comment by FFeei** [comment]
成功了 感谢作者
