### ISSUE TITLE
Play 版微信 8.0.33 依然失效

### ISSUE THREAD

**Issue by AzusaHana** [eritpchy/FingerprintPay#169]
![Screenshot_2023-06-18-16-51-45-62_e39d2c7de19156b0683cd93e8735f348](https://github.com/eritpchy/FingerprintPay/assets/100906636/d518bac3-1d75-4e8d-b43d-3b2eea340eb8)
![Screenshot_2023-06-18-16-51-51-51_e39d2c7de19156b0683cd93e8735f348](https://github.com/eritpchy/FingerprintPay/assets/100906636/29db9239-5791-4c79-8c25-33149ce0cf2e)
模块版本 4.7.3
lsposed 1.8.6(6900)
Log 
[log.txt](https://github.com/eritpchy/FingerprintPay/files/11780994/log.txt)

**Comment by eritpchy** [comment]
8.0.37 zygisk版本实测正常

**Comment by AzusaHana** [comment]
> 8.0.37 zygisk版本实测正常

play还没更新到8037，还在8033，xposed 模块确实不起作用

**Comment by eritpchy** [comment]
可以试试关掉 "Xposed API 调用保护功能" 是否有用

**Comment by AzusaHana** [comment]
> 可以试试关掉 "Xposed API 调用保护功能" 是否有用

测试一样，无效

**Comment by eritpchy** [comment]
8.0.33 xposed版本实测正常

**Comment by ShirokaneShizuku** [comment]
> 8.0.33 xposed版本实测正常

Play Store 版本吗？之前 4.7.0 的时候找不到入口

**Comment by eritpchy** [comment]
是的, 而且近期根本没改过相关内容, 一直都是可用状态, 为什么你们那么喜欢xposed 不怕被检测框架吗, zygisk模块 footprint那么小不香吗

**Comment by ShirokaneShizuku** [comment]
之前是用 LSPosed 的模塊來著，主要是覺得方便。那您的意思是盡量使用 Zygisk 版本嗎

Jason ***@***.***> 于 2023年6月21日周三 11:43写道：

**Comment by eritpchy** [comment]
内容基本一样, 只不过前者多一个框架, 看你自己喜好

**Comment by eritpchy** [comment]
初步怀疑是环境问题, 有人反馈重装wx突然就好了, 其实就跟重启, 结束应用是类似的原理

**Comment by AzusaHana** [comment]
> 初步怀疑是环境问题, 有人反馈重装wx突然就好了, 其实就跟重启, 结束应用是类似的原理

Play 版已更新至 8.0.37，可以正常使用 Xposed 版，将关闭该问题
