### ISSUE TITLE
你好，最新的4.7.3不支持淘宝10.25版本

### ISSUE THREAD

**Issue by andobear** [eritpchy/FingerprintPay#170]
我试了下10.24.0和10.24.15和10.24.20等等都不行，只能10.23的可以

**Comment by N2022062** [comment]
10.24.20.33 無效

**Comment by Gokou-Ruri** [comment]
Google Play的最新版淘宝v10.24.20.33也是一样的情况，淘宝的更新日期为2023.6.6。

**Comment by eritpchy** [comment]
old
