### ISSUE TITLE
云闪付转账场景，弹出多个指纹验证框

### ISSUE THREAD

**Issue by EdiTurn** [eritpchy/FingerprintPay#172]
模块版本：Zygisk 4.7.3
云闪付版本：9.3.4 Play 版
遇到问题：云闪付转账，会弹出多个指纹认证框，其他场景目前未发现此问题。

**Comment by EdiTurn** [comment]
https://github.com/eritpchy/FingerprintPay/assets/5492805/9a47ecc3-525f-49a7-b69b-11704ae82b68

视频里第一次支付我手动取消了，可以看到是弹了两遍弹窗（两个模块弹窗，两个系统界面弹窗，而且模块弹窗需要通过返回手势取消，点按其左上角的叉无反应）；第二次验证指纹转账成功了，但仍有弹窗留存。

**Comment by eritpchy** [comment]
嗯

**Comment by eritpchy** [comment]
fixed in 4.8.0
