### ISSUE TITLE
【功能请求】希望适配微信【服务】相关页面

### ISSUE THREAD

**Issue by Hovn** [eritpchy/FingerprintPay#176]
希望能适配微信【服务】相关页面，自动点击使用密码，然后进行指纹识别填充。参照下图，
微信版本：8.0.40(2420)
1、自动点击图2的“使用密码”。com.tencent.mm.plugin.walletlock.fingerprint.ui.FingerprintWalletLockUI
2、图3中用指纹识别代替。com.tencent.mm.plugin.wallet.pwd.ui.WalletLockCheckPwdUI

图：
![image](https://github.com/eritpchy/FingerprintPay/assets/6801952/c2bad4ca-6297-4b9d-82d0-b6df27fe51d6)

**Comment by eritpchy** [comment]
没有必要, 有些功能还是输密码的好
