### ISSUE TITLE
微信最新版本使用插件后支付时指纹图标和密码键盘一起出

### ISSUE THREAD

**Issue by hrqhhrz** [eritpchy/FingerprintPay#178]
微信版本8.0.40，出现如图效果
![790f9fe06750441359a534cf6fe964fa](https://github.com/eritpchy/FingerprintPay/assets/58965222/61edd819-6c98-4094-98e2-2d7f9309f97c)

**Comment by hrqhhrz** [comment]
补充：这个问题只会在充值/提现零钱和转入/转出零钱通的时候出现，给其他人转账、发红包和扫码付款时正常

**Comment by m8458246** [comment]
试了下，提现和零钱通转出确实会这样，而且按那个指纹也没用，还是得输密码，求大佬有时间的时候看看咋回事儿

**Comment by eritpchy** [comment]
fixed in 4.8.0
