### ISSUE TITLE
微信8.0.42_2460 28002A54兼容性问题

### ISSUE THREAD

**Issue by SoulGI** [eritpchy/FingerprintPay#180]
微信版本：8.0.42_2460 28002A54
模块版本：4.7.5
问题：模块正常加载，指纹识别正常，但是好像不会自动输密码了。
具体表现：支付时验证指纹后会卡在输密码的等待界面，关闭指纹支付后手动输入支付密码可以正常支付。

**Comment by SoulGI** [comment]
补充：模块已尝试重装，微信本体由于个人原因暂无法重装尝试

**Comment by eritpchy** [comment]
如果你不幸升级了新版本发现不兼容, 可以使用MT管理器强制安装旧版本, 不需要清除数据.

**Comment by SoulGI** [comment]
自动更新都是关的，用工具确认了一下像是热更新（最后一次安装式更新是21号的晚上将近18：30，但是同一天的20：30我在测试效果的这个时间点的指纹支付都还是正常的），我不太确定退版本后会不会被再次热更新

**Comment by eritpchy** [comment]
👌

**Comment by Eternally-god** [comment]
我也遇到了这个问题

**Comment by JYBWOB** [comment]
一样的问题，最近先不用了，等等作者更新吧

**Comment by N2022062** [comment]
.37play可以使用麽？

**Comment by eritpchy** [comment]
什么场景 录屏看看

**Comment by Jimlrddcgnfud** [comment]
同样遇到此问题，可以打开指纹支付。扫码付款后跳出指纹识别窗口，识别指纹后停留在密码输入框。

**Comment by Jimlrddcgnfud** [comment]
> 微信版本：8.0.42_2460 28002A54 模块版本：4.7.5 问题：模块正常加载，指纹识别正常，但是好像不会自动输密码了。 具体表现：支付时验证指纹后会卡在输密码的等待界面，关闭指纹支付后手动输入支付密码可以正常支付。

前几天更新插件后也遇到了这个问题，刚刚再试一次又能用了。

**Comment by gcjmail** [comment]
同样的问题，8.0.43

**Comment by JYBWOB** [comment]
> 什么场景 录屏看看

发到你eritpchy@qq.com邮箱了哈

**Comment by xiaozhen12138** [comment]
我也遇到过这个问题，微信版本也是国内8.0.42，支付时验证指纹震动了但是没有自动输入密码，后来运行了个QQ微信清理脚本重新打开微信设置好就又可以用了

**Comment by SoulGI** [comment]
作者已发版解决，issue我主动关闭
