### ISSUE TITLE
怎么不支持谷歌版QQ了

### ISSUE THREAD

**Issue by woshishiq1** [eritpchy/FingerprintPay#182]
…。。。。。

**Comment by eritpchy** [comment]
什么问题

**Comment by woshishiq1** [comment]
谷歌版QQ8.2.11没有指纹设置了，升级最新版后

**Comment by eritpchy** [comment]
fixed https://file.xdow.net/fingerprintpay/4.8.2/zygisk-module-xfingerprint-pay-qq-v4.8.2-release.zip
