### ISSUE TITLE
云闪付支付成功后再次弹出指纹验证

### ISSUE THREAD

**Issue by dreamy06** [eritpchy/FingerprintPay#183]
模块版本：xposed 4.8.1
安卓版本：14
云闪付版本：9.3.8(3121) play
遇到问题：云闪付支付成功后，再次弹出指纹验证；另外转账场景是正常的

https://github.com/eritpchy/FingerprintPay/assets/36306588/e1e66567-293f-4f76-bb30-d1c1a4af3037

**Comment by eritpchy** [comment]
https://file.xdow.net/fingerprintpay/4.8.2 试试

**Comment by dreamy06** [comment]
> https://file.xdow.net/fingerprintpay/4.8.2 试试

感谢， 没问题了
