### ISSUE TITLE
改用zgisk next，指纹支付模块没法识别到。

### ISSUE THREAD

**Issue by chaofanlin** [eritpchy/FingerprintPay#184]
刷zgisk next模块关掉了原zigisk，来替代原zigisk。
现在指纹支付模块识别不到zgisk next。
显示“Zygisk未启动，此模块暂停加载”
像shamiko其它模块是可以正常。

[如图](https://i2.100024.xyz/2023/11/08/hiq9g7.webp)

**Comment by chaofanlin** [comment]
magisk版本：delta-26301
指纹支付模块：v4.8.1

**Comment by dreamy06** [comment]
我用alpha正常加载，虽然一样显示暂停加载，但是正常使用。

还有你的那个shamiko并没有加载，正常应该显示"blacklist mode"或者"whitelist mode"，实际上delta并不兼容shamiko。

所以这个应该是delta的问题，你用自带zygisk就行了

**Comment by chaofanlin** [comment]
> 我用alpha正常加载，虽然一样显示暂停加载，但是正常使用。
> 
> 还有你的那个shamiko并没有加载，正常应该显示"blacklist mode"或者"whitelist mode"，实际上delta并不兼容shamiko。
> 
> 所以这个应该是delta的问题，你用自带zygisk就行了

感谢。
[图片](https://i2.100024.xyz/2023/11/08/k5g0xx.webp)
没办法，只能做取舍了

**Comment by eritpchy** [comment]
已经确认 KernelSU + Zygisk Next + 指纹支付4.8.1兼容的, 可以正常使用

**Comment by eritpchy** [comment]
README 已更新
