### ISSUE TITLE
安卓10通过logcat发现以下日志

### ISSUE THREAD

**Issue by RinggaV** [eritpchy/FingerprintPay#185]
今天手机莫名其妙黑屏死机了, 强制重启后查看日志得到下述, 是否与该插件有关呢, 不兼容吗? 我需要回退版本吗:
--------- beginning of crash
12-08 09:00:56.429  4098  4098 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4098 (init), pid 4098 (init)
12-08 09:00:56.499  4098  4098 F libc    : crash_dump helper failed to exec
12-08 09:06:51.883   622   622 F libc    : crash_dump helper failed to exec
12-08 09:06:55.647  3207  3218 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 3218 (Signal Catcher), pid 3207 (ndroid.systemui)
12-08 09:06:55.789 15453 15453 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
12-08 09:06:55.789 15453 15453 F DEBUG   : Build fingerprint: 'OnePlus/OnePlus7Pro_CH/OnePlus7Pro:10/QKQ1.190716.003/2102081514:user/release-keys'
12-08 09:06:55.789 15453 15453 F DEBUG   : Revision: '0'
12-08 09:06:55.789 15453 15453 F DEBUG   : ABI: 'arm64'
12-08 09:06:55.789 15453 15453 F DEBUG   : Timestamp: 2023-12-08 09:06:55+0800
12-08 09:06:55.789 15453 15453 F DEBUG   : pid: 3207, tid: 3218, name: Signal Catcher  >>> com.android.systemui <<<
12-08 09:06:55.789 15453 15453 F DEBUG   : uid: 10053
12-08 09:06:55.789 15453 15453 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
12-08 09:06:55.789 15453 15453 F DEBUG   : Abort message: 'Check failed: key_value != nullptr compiler-filter not found in oat header'
12-08 09:06:55.789 15453 15453 F DEBUG   :     x0  0000000000000000  x1  0000000000000c92  x2  0000000000000006  x3  0000007db627a780
12-08 09:06:55.789 15453 15453 F DEBUG   :     x4  0000007e4c631000  x5  0000007e4c631000  x6  0000007e4c631000  x7  0000000000013fe2
12-08 09:06:55.789 15453 15453 F DEBUG   :     x8  00000000000000f0  x9  b44658b17bf11428  x10 0000000000000001  x11 0000000000000000
12-08 09:06:55.789 15453 15453 F DEBUG   :     x12 fffffff0fffffbdf  x13 ffffffff9a8d956d  x14 0000000002f87b91  x15 0000007e46934000
12-08 09:06:55.789 15453 15453 F DEBUG   :     x16 0000007e4692a738  x17 0000007e46908be0  x18 0000007d66364000  x19 0000000000000c87
12-08 09:06:55.789 15453 15453 F DEBUG   :     x20 0000000000000c92  x21 00000000ffffffff  x22 0000007dc4ea9210  x23 0000007dc489e645
12-08 09:06:55.789 15453 15453 F DEBUG   :     x24 0000007dc48c01c1  x25 0000000000000001  x26 0000007dc543c258  x27 0000007dc60fe7f0
12-08 09:06:55.789 15453 15453 F DEBUG   :     x28 0000007dc60decd0  x29 0000007db627a820
12-08 09:06:55.789 15453 15453 F DEBUG   :     sp  0000007db627a760  lr  0000007e468ba404  pc  0000007e468ba430
12-08 09:06:55.791 15453 15453 F DEBUG   :
12-08 09:06:55.791 15453 15453 F DEBUG   : backtrace:
12-08 09:06:55.791 15453 15453 F DEBUG   :       #00 pc 0000000000073430  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: a2584ee8458a61d422edf24b4cd23b78)
12-08 09:06:55.791 15453 15453 F DEBUG   :       #01 pc 00000000004b95f4  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x3eb000) (art::Runtime::Abort(char const*)+2280) (BuildId: bdffe04c611dbc98c8441c9efc5c6a12)
12-08 09:06:55.791 15453 15453 F DEBUG   :       #02 pc 000000000000b458  /system/lib64/libbase.so (android::base::LogMessage::~LogMessage()+580) (BuildId: 1efae6b19d52bd307d764e26e1d0e2c9)
12-08 09:06:55.791 15453 15453 F DEBUG   :       #03 pc 00000000004464b8  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x3eb000) (art::OatHeader::GetCompilerFilter() const+280) (BuildId: bdffe04c611dbc98c8441c9efc5c6a12)
12-08 09:06:55.791 15453 15453 F DEBUG   :       #04 pc 000000000044dde0  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x3eb000) (art::OatFile::GetCompilerFilter() const+40) (BuildId: bdffe04c611dbc98c8441c9efc5c6a12)
12-08 09:06:55.791 15453 15453 F DEBUG   :       #05 pc 0000000000459550  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x3eb000) (art::OatFileManager::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char>>&)+392) (BuildId: bdffe04c611dbc98c8441c9efc5c6a12)
12-08 09:06:55.791 15453 15453 F DEBUG   :       #06 pc 00000000004c69c0  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x3eb000) (art::Runtime::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char>>&)+104) (BuildId: bdffe04c611dbc98c8441c9efc5c6a12)
12-08 09:06:55.791 15453 15453 F DEBUG   :       #07 pc 00000000004dae58  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x3eb000) (art::SignalCatcher::HandleSigQuit()+1352) (BuildId: bdffe04c611dbc98c8441c9efc5c6a12)
12-08 09:06:55.791 15453 15453 F DEBUG   :       #08 pc 00000000004d9f04  /apex/com.android.runtime/lib64/libart.so!libart.so (offset 0x3eb000) (art::SignalCatcher::Run(void*)+252) (BuildId: bdffe04c611dbc98c8441c9efc5c6a12)
12-08 09:06:55.791 15453 15453 F DEBUG   :       #09 pc 00000000000d6b70  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: a2584ee8458a61d422edf24b4cd23b78)
12-08 09:06:55.791 15453 15453 F DEBUG   :       #10 pc 0000000000074eac  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: a2584ee8458a61d422edf24b4cd23b78)
12-08 09:07:06.362  3848  3883 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 3883 (Signal Catcher), pid 3848 (m.android.phone)

**Comment by eritpchy** [comment]
模块版本 系统版本 目标软件版本 问题复现路径(文字+视频描述更好(若有)) 复现概率

**Comment by eritpchy** [comment]
完整日志文件

**Comment by eritpchy** [comment]
关掉lsp

**Comment by jcsolely** [comment]
没安装lsp，只有magisk

**Comment by eritpchy** [comment]
![18221708416633_ pic](https://github.com/eritpchy/FingerprintPay/assets/8630635/73a4b418-6051-473c-8f5f-688911b4036e)
我就没装这几个插件一样卡, 跟“指纹插件本身”没关系
BTW 小米手机不需要这个插件本来就能用
