### ISSUE TITLE
支付宝10.5.55.8000 转账不能指纹支付

### ISSUE THREAD

**Issue by ucxl** [eritpchy/FingerprintPay#186]
大大 支付宝10.5.55.8000 转账不能指纹支付

**Comment by Goojoe** [comment]
我也是 10.5.55.9600

**Comment by TLSMars** [comment]
同样的问题

**Comment by eritpchy** [comment]
[5.2.0](https://github.com/eritpchy/FingerprintPay/releases/tag/5.2.0-ci)
