### ISSUE TITLE
指纹支付时第一次失败

### ISSUE THREAD

**Issue by RFdada** [eritpchy/FingerprintPay#188]
指纹支付时第一次失败，得切换支付方式重新用指纹支付才能成功

**Comment by eritpchy** [comment]
抓下日志

**Comment by 1753135250** [comment]
一样一样

**Comment by 1753135250** [comment]
[Uploading com.tencent.mm-2024-01-27-23-36-16.log…]()

**Comment by 1753135250** [comment]
> 抓下日志

[Uploading com.tencent.mm-2024-01-27-23-36-16.log…]()

**Comment by 1753135250** [comment]
> 抓下日志
[com.tencent.mm-2024-01-27-23-36-16.log](https://github.com/eritpchy/FingerprintPay/files/14083768/com.tencent.mm-2024-01-27-23-36-16.log)

**Comment by JYBWOB** [comment]
一样的情况

**Comment by Marukon** [comment]
关掉显示指纹图标试试

**Comment by JYBWOB** [comment]
> 关掉显示指纹图标试试

原本就没开指纹图标显示

**Comment by JYBWOB** [comment]
> > 抓下日志
> > [com.tencent.mm-2024-01-27-23-36-16.log](https://github.com/eritpchy/FingerprintPay/files/14083768/com.tencent.mm-2024-01-27-23-36-16.log)

> 指纹支付时第一次失败，得切换支付方式重新用指纹支付才能成功


两位解决了吗 @RFdada @1753135250

**Comment by eritpchy** [comment]
[5.2.0](https://github.com/eritpchy/FingerprintPay/releases/tag/5.2.0-ci)
