### ISSUE TITLE
请求适配云闪付10.0版本

### ISSUE THREAD

**Issue by EdiTurn** [eritpchy/FingerprintPay#189]
云闪付版本：10.0.1 play 版
模块版本：5.0.1 Zygisk

近日云闪付更新了 10.0 版，此版本使用模块支付时，付款方式选择界面会一闪而过并直接弹出指纹验证，若取消指纹验证重新选择付款卡，则只能输入密码。

https://github.com/eritpchy/FingerprintPay/assets/5492805/42ef2c14-f0ac-4a02-9305-bac823324a68

**Comment by eritpchy** [comment]
1

**Comment by EdiTurn** [comment]
更新到 5.1.0 后，以上问题仍然存在，云闪付版本为 10.0.8

**Comment by eritpchy** [comment]
测了下 这个功能适配太多bug，我又回滚了,所以 目前还是只能默认方式

**Comment by eritpchy** [comment]
[5.2.0](https://github.com/eritpchy/FingerprintPay/releases/tag/5.2.0-ci)

**Comment by EdiTurn** [comment]
5.2.0 使用反馈：
指纹验证提前弹出的问题仍然存在，好在更换支付方式/优惠方式后能够再次弹出指纹验证。

此外，此版本微信/云闪付都存在第一次指纹验证必然失败，第二次才会成功的问题，在指纹设置中重设一边支付密码后解决。
