### ISSUE TITLE
Alipay版本10.5.66.9100用不了

### ISSUE THREAD

**Issue by sunday123** [eritpchy/FingerprintPay#191]
一直以来用fingerprintpay 4.7.5 版本， 1月底更新Alipay到10.5.66.9100版本，直到前三四天指纹才发现不可用了。

目前，fingerprintpay更新到4.8.1和5.0.1都发现不可用。重置支付密码时候出现过指纹提示，但其他支付场合支付时候都没有指纹提示。

**Comment by jcsolely** [comment]
指纹设置显示，支付时无指纹界面，之间弹出密码框

**Comment by N2022062** [comment]
play 10.5.70.9500失效

**Comment by sunday123** [comment]
替换旧版本alipay，暂时解决问题

**Comment by N2022062** [comment]
> 替换旧版本alipay，暂时解决问题

具體哪版？我是了23年12月的版本都不行

**Comment by sunday123** [comment]
> > 替换旧版本alipay，暂时解决问题
> 
> 具體哪版？我是了23年12月的版本都不行

version 10.5.30.9100
com.eg.android.AlipayGphone
FingerprintPay版本4.8.1
