### ISSUE TITLE
支付宝指纹支付不可用

### ISSUE THREAD

**Issue by LynBucket** [eritpchy/FingerprintPay#193]
模组版本 4.8.0
支付宝版本 play版 10.5.70
Magisk+Zygisk

有指纹设置的选项，但设置完成后支付时依然只能输入密码

**Comment by LynBucket** [comment]
尝试应用宝下载最新版，问题依旧。
普通支付，转账指纹不可用，但添加支付宝余额可以。

**Comment by xi8964** [comment]
解决办法：https://github.com/eritpchy/FingerprintPay/issues/196

**Comment by eritpchy** [comment]
[5.2.0](https://github.com/eritpchy/FingerprintPay/releases/tag/5.2.0-ci)
