### ISSUE TITLE
无法理解为什么要给密码。没办法调用谷歌的验证，或者调用微信的验证吗？

### ISSUE THREAD

**Issue by shmily103** [eritpchy/FingerprintPay#195]
无法理解为什么要给密码。没办法调用谷歌的验证，或者调用微信的验证吗？

或者做一个诱骗，让微信调用谷歌的验证没办法做到吗？

直接给密码是一个很不安全的动作。

**Comment by eritpchy** [comment]
嗯, 很好的建议, 等您PR一个不用密码的补丁过来

**Comment by shmily103** [comment]
。
