### ISSUE TITLE
支付宝指纹支付不可用，求作者修复

### ISSUE THREAD

**Issue by z729919391** [eritpchy/FingerprintPay#197]
指纹支付版本4.8.1，支付宝版本10.5.90，模块已安装到位，微信淘宝等可正常使用，支付宝显示已开启但无法使用

**Comment by eritpchy** [comment]
该版本尚未适配, 请用10.5.30.9100版本

**Comment by eritpchy** [comment]
[5.2.0](https://github.com/eritpchy/FingerprintPay/releases/tag/5.2.0-ci)
