### ISSUE TITLE
5.10版本支付页面会弹出密码键盘

### ISSUE THREAD

**Issue by zhuxiao668** [eritpchy/FingerprintPay#198]
![IMG_20240524_211517.jpg](https://github.com/eritpchy/FingerprintPay/assets/156587915/ce0be64c-19f8-4252-805a-510287339a08)

4.81版本

**Comment by zhuxiao668** [comment]
![Screenshot_2024-05-24-21-16-22-52_e39d2c7de19156b0683cd93e8735f348.jpg](https://github.com/eritpchy/FingerprintPay/assets/156587915/905b753e-0c4c-4a90-9468-9970afa35201)

5.10版本

**Comment by eritpchy** [comment]
微信版本+操作路径

**Comment by zhuxiao668** [comment]
> 微信版本+操作路径

8.0.45（2521），lsp框架

**Comment by eritpchy** [comment]
<img width="452" alt="image" src="https://github.com/eritpchy/FingerprintPay/assets/8630635/a306559d-dfd6-4915-a38e-ad1904304283">
8.0.45没测过 请升级到8.0.49(2600)或以上版本试试,

**Comment by zhuxiao668** [comment]
> <img width="452" alt="image" src="https://github.com/eritpchy/FingerprintPay/assets/8630635/a306559d-dfd6-4915-a38e-ad1904304283">
> 8.0.45没测过 请升级到8.0.49(2600)或以上版本试试,

8.0.49（2600）还是会弹

**Comment by zhuxiao668** [comment]
![IMG_20240525_124218.jpg](https://github.com/eritpchy/FingerprintPay/assets/156587915/10b63d3d-6ade-488f-b08b-3468c1636e30)

**Comment by eritpchy** [comment]
<img width="449" alt="image" src="https://github.com/eritpchy/FingerprintPay/assets/8630635/a9958a20-a931-43ae-8e83-3b5add178538">
录视频 发日志

**Comment by zhuxiao668** [comment]
> <img width="449" alt="image" src="https://github.com/eritpchy/FingerprintPay/assets/8630635/a9958a20-a931-43ae-8e83-3b5add178538">
> 录视频 发日志

发邮箱了👌

**Comment by eritpchy** [comment]
需要重新录入支付密码再试试

**Comment by zhuxiao668** [comment]
还是不行😂

**Comment by eritpchy** [comment]
[xposed.com.surcumference.fingerprintpay.wechatfp.5.1.1.release.apk.zip](https://github.com/eritpchy/FingerprintPay/files/15441828/xposed.com.surcumference.fingerprintpay.wechatfp.5.1.1.release.apk.zip)
1. 安装此版本
2. 进入微信设置查看指纹支付版本是否为5.1.1
3. 进入设置中重设支付密码(必须)
4. 再支付试一试, 不成功再抓日志发我

**Comment by eritpchy** [comment]
刚刚那个搞错了, 再试试5.1.2, 重设支付密码还是必要的

**Comment by zhuxiao668** [comment]
> 刚刚那个搞错了, 再试试5.1.2, 重设支付密码还是必要的

刚刚试了面具版，正常 没有弹窗

**Comment by eritpchy** [comment]
什么叫没有弹窗

**Comment by zhuxiao668** [comment]
> 什么叫没有弹窗

就是不弹密码键盘了😂![Screenshot_2024-05-25-14-11-18-28_e39d2c7de19156b0683cd93e8735f348.jpg](https://github.com/eritpchy/FingerprintPay/assets/156587915/ac1fcbd4-2876-464c-80cd-80dc84703ee3)

**Comment by eritpchy** [comment]
能支付吗！？

**Comment by zhuxiao668** [comment]
> 能支付吗！？

可以的

**Comment by eritpchy** [comment]
好的

**Comment by eritpchy** [comment]
http://file.xdow.net/fingerprintpay/5.2.0-dev/xposed.com.surcumference.fingerprintpay.wechatfp.5.2.0.release.apk
试试看, 可以吧你以前用过的屏幕解锁方式加回来了

**Comment by N2022062** [comment]
密碼要重新設置一次，但是彈出的支付界面沒指紋圖標。

**Comment by eritpchy** [comment]
> 密碼要重新設置一次，但是彈出的支付界面沒指紋圖標。
通用设置自行打开

**Comment by eritpchy** [comment]
> 密碼要重新設置一次，但是彈出的支付界面沒指紋圖標。

@N2022062 通用设置自行打开

**Comment by eritpchy** [comment]
[5.2.0](https://github.com/eritpchy/FingerprintPay/releases/tag/5.2.0-ci)
