### ISSUE TITLE
微信无法指纹支付

### ISSUE THREAD

**Issue by cccqcccq** [eritpchy/FingerprintPay#200]
**bug描述 Describe the Bug**
刷入模块后还是无法使用

**重现步骤 To Reproduce**
清提供视频或文字描述您出现问题时候的操作路径:
刷入magisk模块5.2版本后重启刷入指纹支付5.2xp模块
进入设置密码后开启支付功能
![398c29fae3a66a13588e42dbb4b2cdd](https://github.com/eritpchy/FingerprintPay/assets/117553354/4fe45637-74d3-4a5d-8be3-c7fbad392d9a)
![565f607e9c849f2d98db3f724e9dc4a](https://github.com/eritpchy/FingerprintPay/assets/117553354/2d8a34cd-3b4c-4fa3-9abe-7e6c5a3d21c5)
![dce40786233ea32b1dfa00d3356d023](https://github.com/eritpchy/FingerprintPay/assets/117553354/7c3d21b9-341c-49fe-ae97-df0f719ada10)
![a8f844709aa7ae4b3fb95ae64e8d00f](https://github.com/eritpchy/FingerprintPay/assets/117553354/b8fa4f88-1ad9-4a5a-a665-ded4bb7ffa98)
尝试过删除所有指纹重新录入
尝试过只刷入magisk和只刷入xp模块

**环境信息 Environment Information**
 - 设备名称: [1+ace3]
 - 系统版本: [ColorOS 14]
 - 插件版本: [5.2.0]
 - 插件类型: [zygisk/xposed]
 - 应用名称: [微信]
 - 应用版本: [8.0.49]

**Comment by eritpchy** [comment]
👍
