### ISSUE TITLE
微信每次指纹识别之前会先弹窗报错

### ISSUE THREAD

**Issue by Yish1** [eritpchy/FingerprintPay#201]
**bug描述 Describe the Bug**
微信每次指纹识别之前会先弹窗报错，关闭弹窗后，点击输入密码才可使用模块的指纹识别，

**重现步骤 To Reproduce**
清提供视频或文字描述您出现问题时候的操作路径:
![S40715-09473818_com tencent mm](https://github.com/user-attachments/assets/b520a92c-297d-466a-83f3-b2f4e0f6ca7a)

**环境信息 Environment Information**
 - 设备名称: 魅族21
 - 系统版本: flymeaios
 - 插件版本: [5.2.0]
 - 插件类型: [zygisk
 - 应用名称: 微信
 - 应用版本: 8.0.49

**其他补充信息 Additional Supplementary Information**
如果你还有其他需要补充的内容，请写在这里。

**Comment by eritpchy** [comment]
请录屏

**Comment by Yish1** [comment]
> 请录屏


https://github.com/user-attachments/assets/4faa0362-3cac-4548-9c49-c9d0449cd0f6

**Comment by eritpchy** [comment]
进服务 需要密码? 这是你自己设置的吧, 我们进服务不需要密码

**Comment by Yish1** [comment]
> 进服务 需要密码? 这是你自己设置的吧, 我们进服务不需要密码

不是，只是拿服务举个例（收付款那个也是），我这所有的指纹场景都有这个弹窗，要手动点一次输入支付密码才行

**Comment by eritpchy** [comment]
看起来是因为你以前开通过微信的指纹支付, 现在因为某种原因(比如解锁)微信的指纹支付用不了, 建议您 备份微信卸载重装, 或者关闭微信指纹支付尝试哦

**Comment by Yish1** [comment]
感谢，已通过关闭微信自带指纹支付功能解决
