### ISSUE TITLE
微信指纹支付无法使用

### ISSUE THREAD

**Issue by Suni-code** [eritpchy/FingerprintPay#202]
**bug描述 Describe the Bug**
无法开通指纹支付
![Screenshot_2024-07-15-12-11-39-56_785cfb1f0fb0c9a2030c9b38a1c3479a.jpg](https://github.com/user-attachments/assets/ed474a1e-7041-4141-9f9d-a6430f25bf49)

![Screenshot_2024-07-15-12-12-13-00_e39d2c7de19156b0683cd93e8735f348.jpg](https://github.com/user-attachments/assets/d986c7a2-b632-4580-8d15-bb31585942e6)

**重现步骤 To Reproduce**
清提供视频或文字描述您出现问题时候的操作路径:
打开微信-我-服务-钱包-支付设置-开通指纹支付

**环境信息 Environment Information**
 - 设备名称: [Oneplus 9 Pro]
 - 系统版本: [ColorOS 14]
 - 插件版本: [5.2.0]
 - 插件类型: [zygisk]
 - 应用名称: [微信]
 - 应用版本: [8.0.50(2701)]

**其他补充信息 Additional Supplementary Information**
如果你还有其他需要补充的内容，请写在这里。

**Comment by eritpchy** [comment]
这个模块不负责开通指纹支付, 请看教程操作
