### ISSUE TITLE
支付时先触发输入密码，选择支付方式再返回才会触发指纹支付

### ISSUE THREAD

**Issue by SakuraKyuo** [eritpchy/FingerprintPay#204]
**bug描述 Describe the Bug**
微信支付时会先触发输入密码，点击支付方式然后返回才会触发指纹支付

**重现步骤 To Reproduce**
以微信转账为例，微信会先拉起输入密码的窗口，然后手动点击支付方式，再返回才可以触发指纹支付

**环境信息 Environment Information**
 - 设备名称: [Oneplus Ace 3 Pro]
 - 系统版本: [ColorOS 14]
 - 插件版本: [5.2.0]
 - 插件类型: [zygisk/xposed]
 - 应用名称: [微信]
 - 应用版本: [8.0.50]

**其他补充信息 Additional Supplementary Information**
仅在Ace 3 Pro的微信支付复现过该问题，如需log请回复issue提供

**Comment by eritpchy** [comment]
请提供操作视频以及日志

**Comment by DownPower** [comment]
> 请提供操作视频以及日志


https://github.com/user-attachments/assets/54a20a9f-6022-45d3-a1ed-109c07e66e98
[com.tencent.mm-2024-08-14-15-50-32.log](https://github.com/user-attachments/files/16609314/com.tencent.mm-2024-08-14-15-50-32.log)

**Comment by eritpchy** [comment]
zygisk版本试试

**Comment by SakuraKyuo** [comment]
> 请提供操作视频以及日志


https://github.com/user-attachments/assets/ad6e0cd9-2141-4d40-9338-1c463c9e8de8

[com.tencent.mm-2024-08-14-15-49-21.log](https://github.com/user-attachments/files/16609517/com.tencent.mm-2024-08-14-15-49-21.log)

正在使用Zygisk版本

**Comment by eritpchy** [comment]
日志显示你用的还是Xposed版本, 请卸载Xposed版本试试Zygisk版本
