### ISSUE TITLE
为多个账户设置不同支付密码，或在支付时允许手动输入密码

### ISSUE THREAD

**Issue by Jisu-Woniu** [eritpchy/FingerprintPay#205]
我个人的微信大小号采用不同的支付密码，如果直接切换账号，忘记不关闭指纹支付模块时会一直提示密码错误，无法支付。

希望能提供手动输入密码的功能，或允许为不同账户设置不同支付密码。

**Comment by eritpchy** [comment]
增加该功能会大幅增加适配成本, 请考虑使用相同密码或者分身方案

**Comment by Jisu-Woniu** [comment]
那可以在指纹识别界面增加一个手动输入按钮

**Comment by eritpchy** [comment]
点击软件自带的指纹 图标会切换到密码输入

**Comment by Jisu-Woniu** [comment]
> 点击软件自带的指纹 图标会切换到密码输入

谢谢
