### ISSUE TITLE
微信版本8.0.50，Magisk+Zygisk指纹支付-微信，无法使用

### ISSUE THREAD

**Issue by DownPower** [eritpchy/FingerprintPay#206]
**bug描述 Describe the Bug**
微信版本8.0.50，Magisk+Zygisk指纹支付-微信，无法使用

**重现步骤 To Reproduce**
刷入Zygisk版本5.2.0

**环境信息 Environment Information**
 - 设备名称: [OnePlus Ace3]
 - 系统版本: [ColorOS 14]
 - 插件版本: [5.2.0]
 - 插件类型: [zygisk]
 - 应用名称: [微信]
 - 应用版本: [8.0.50]

**其他补充信息 Additional Supplementary Information**

![fcaef2dcef0d68d2237293f0bc13ac1](https://github.com/user-attachments/assets/6a0fc2ae-9e09-48a6-aa8b-1d6150d728e8)
![0008a3027d7a33dd3291bf42b4abc70](https://github.com/user-attachments/assets/9d4598bd-198e-41cc-b61a-e72f105208e1)
![df85bc3124125a1abef19f2646415fc](https://github.com/user-attachments/assets/06c49846-e030-4740-9305-d6819c9d5086)

**Comment by eritpchy** [comment]
https://github.com/eritpchy/FingerprintPay/tree/main/doc/WeChat

**Comment by DownPower** [comment]
> https://github.com/eritpchy/FingerprintPay/tree/main/doc/WeChat
已设置，仍然不生效
https://github.com/eritpchy/FingerprintPay/issues/206#issuecomment-2285270618
