### ISSUE TITLE
微信支付界面提示多次密码错误

### ISSUE THREAD

**Issue by gally16** [eritpchy/FingerprintPay#77]
[IMG]http://i63.tinypic.com/28743t1.jpg[/IMG]

进入支付界面后大概3秒才弹出“多次密码错误”，实际什么都没输入
支付宝就没问题
指纹支付3.92
微信6.67
安卓8.0
三星S9+

**Comment by eritpchy** [comment]
重启手机

**Comment by gally16** [comment]
> 重启手机

重启过了还是一样-_-

**Comment by eritpchy** [comment]
close old bug
