### ISSUE TITLE
希望可以在进行指纹支付时自动将屏幕亮度调到最大

### ISSUE THREAD

**Issue by Gokou-Ruri** [eritpchy/FingerprintPay#92]
系统版本：Android 11 (Evolution X 5.3 | Lightning | OFFICIAL)
机型：Redmi k20 Pro
指纹：屏下
微信版本：7.0.21 (Google Play)
支付宝版本：10.2.13.7000 (Google Play)
淘宝版本：9.13.1 (Google Play)
QQ版本：8.2.10 (Google Play)
Xposed安装器版本：LSPosed 0.5.4.0 (5135)
Xposed框架版本：0.5.4.0 (5175)
模块作用域：仅勾选如上4个支付程序

目前微信可用，一切正常。其它3个支付程序均不可用，具体表现为支付时，反复提示指纹识别失败，只能使用密码支付。
尝试过禁用Xposed模块，改用Magisk(Ruri)模块，问题依旧，只有微信能正常进行指纹识别。

**Comment by Gokou-Ruri** [comment]
破案了，是由于屏幕亮度不够导致指纹识别失败……
希望开发者可以让支付宝/淘宝/QQ在指纹识别时自动把亮度调到最高（关闭自动亮度并调高亮度），支付完以后再恢复原来的亮度。

**Comment by eritpchy** [comment]
👍🏻

**Comment by lerogo** [comment]
别搞呀 得把眼睛亮瞎

**Comment by mclovin-2k** [comment]
“自动将屏幕指纹识别区域的亮度调到最大”。这个是实现不了的，因为App只能调整整个窗口的亮度。
由于亮度不够导致指纹识别不出来，明显这是你的设备Rom的问题。
应该向ROM作者反馈。

**Comment by eritpchy** [comment]
全屏可以, 区域不行
