### ISSUE TITLE
淘宝和闲鱼指纹失效

### ISSUE THREAD

**Issue by Cyberxxt** [eritpchy/FingerprintPay#93]
![Screenshot_2021-08-06-15-43-17-864_com taobao idlefish](https://user-images.githubusercontent.com/40683077/128475397-835b9ad2-c5cd-4fe7-b5ed-08ddde7bd872.jpg)

如图，淘宝和闲鱼支付时直接填密码键盘了
但是支付宝转账和扫码支付的时候还可以用指纹，不知道是怎么回事
淘宝为Play版10.1.10.25

**Comment by eritpchy** [comment]
支付宝和淘宝不是同一套程序,  请等待更新

**Comment by eritpchy** [comment]
闲鱼更新后似乎内嵌了支付sdk, 而不是调用外部支付宝进行支付, 应该不支持了

**Comment by eritpchy** [comment]
fixed, 淘宝only https://github.com/eritpchy/FingerprintPay/releases/tag/4.0.0
