### ISSUE TITLE
4.0.0支付宝magisk模块提示密码错误。

### ISSUE THREAD

**Issue by fang5566** [eritpchy/FingerprintPay#94]
设备：OnePlus 7
系统：类原生yaap
支付宝版本：10.2.28(GooglePlay)
Magisk：23.0
Riru：26.1.1
magisk模块版本：4.0.0

支付宝magisk模块，输入支付密码正确，指纹匹配成功但提示密码错误，弹出支付宝密码输入框。退回3.9.22正常。

怀疑是模块问题，密码本地保存不正确导致支付宝识别为错误支付密码。

**Comment by eritpchy** [comment]
装了指纹支付app吗

**Comment by fang5566** [comment]
没装指纹app，就是直接看到更新提示，就从github下载4.0覆盖安装。微信指纹支付4.0没问题。支付宝模块回退3.9.22也没问题就是没适配不好看。全程没装指纹app，也没装指纹xposed模块

**Comment by eritpchy** [comment]
回头看看， 可以尝试清除支付宝数据，有条件可以抓下logcat发我

**Comment by fang5566** [comment]
logcat怎么抓，支付宝为了避免版本问题，我是卸载，然后从新从Google play 下载最新版

**Comment by eritpchy** [comment]
手机usb连接电脑， 打开命令提示符敲adb logcat &gt;c:/1.log&nbsp; &nbsp; &nbsp;接着重设密码并尝试支付一次， 然后把1.log发上来

**Comment by eritpchy** [comment]
支付宝关于读取设备信息(ID)的权限给足试试

**Comment by fang5566** [comment]
所有支付宝的权限都给了，有装xp的thanox,没有开启任何权限限制。支付宝的权限全部都是打勾。

**Comment by fang5566** [comment]
> 手机usb连接电脑， 打开命令提示符敲adb logcat >c:/1.log 接着重设密码并尝试支付一次， 然后把1.log发上来

命令提示符提示拒绝访问

**Comment by fang5566** [comment]
[log.log](https://github.com/eritpchy/FingerprintPay/files/7091998/log.log)

**Comment by eritpchy** [comment]
是不是有Oops. 输出密码失败的提示

**Comment by timberdai** [comment]
+1同样的问题

**Comment by fang5566** [comment]
> 是不是有Oops. 输入密码失败的提示

是的，就是这个提示。

**Comment by eritpchy** [comment]
实锤还未兼容最新版支付宝 6位密码

**Comment by eritpchy** [comment]
[magisk-riru-module-xfingerprint-pay-alipay-v4.0.0-release.zip](https://github.com/eritpchy/FingerprintPay/files/7096005/magisk-riru-module-xfingerprint-pay-alipay-v4.0.0-release.zip)
[magisk-riru-module-xfingerprint-pay-taobao-v4.0.0-release.zip](https://github.com/eritpchy/FingerprintPay/files/7096006/magisk-riru-module-xfingerprint-pay-taobao-v4.0.0-release.zip)
试试看, 顺手也测下淘宝

**Comment by fang5566** [comment]
感谢，支付宝已经可以正常使用了。淘宝没装，回头下载试试。
