### ISSUE TITLE
模块会一直打印FingerprintPay [d](L.java:35) top activity	null

### ISSUE THREAD

**Issue by Oosl** [eritpchy/FingerprintPay#97]
如题
机型：一加9 Pro
系统：ColorOS 11.2
微信：8.0.11
模块：4.0.1
Lsposed: 5982
详细log：https://wwe.lanzoui.com/io2gAtlrr4d

**Comment by eritpchy** [comment]
日志罢了，并不是什么问题，并不影响性能

**Comment by Oosl** [comment]
性能影响倒是不至于，我是因为看到模块日志里全是这玩意觉得不舒服，想着来提一下。

**Comment by eritpchy** [comment]
嗯，你可以自己改改关掉他，这些日志需要留着给一些人排查故障用

**Comment by Oosl** [comment]
嗯嘞，谢啦。
